spring.application.name=order-service

#Server port
server.port=8081

#Eureka settings
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable Feign circuit breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Circuit Breaker configuration
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventory-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventory-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventory-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventory-service.permitted-number-of-calls-in-half-open-state=3

#spring acutator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Kafka Producer Config
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#DB
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=ORDER_USER
spring.datasource.password=order123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect